name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: az-digital/dockertest/dockertest
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        snapshot: true
